### PR TITLE
Fix the build fail "JAVA_HOME is not defined correctly"

### PR DESCRIPTION
**Pull request by develio**

### CODE REVIEW

**Comment by mplacona** [comment]
Thank you so much for your contribution!

**Comment by zixuan75** [comment]
zixuan75/java_project

**Comment by stefanbirkner** [comment]
This change is bad. By explicitly setting JAVA_HOME it overrides the selected JDK. This means that all builds on Travis CI use Java 8 although they should use the specified JDK. I provide a pull request with the real fix for the problem within the next day.

**Comment by zixuan75** [comment]
yes @stefanbirkner

**Pull request merged**
